name: hovernet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pip=24.3.1
  - openslide
  - pip:
    - docopt==0.6.2
    - future==0.18.2
    - imgaug==0.4.0
    - matplotlib==3.9.3
    - numpy==1.26.4
    - opencv-python==4.10.0.84
    - pandas==2.2.3
    - pillow==11.0.0
    - psutil==5.7.3
    - scikit-image==0.24.0
    - scikit-learn==1.6.0
    - scipy==1.14.1
    - tensorboard==2.3.0
    - tensorboardx==2.1
    - termcolor==1.1.0
    - tqdm==4.48.0
    - openslide-python==1.4.1
